### ISSUE TITLE
Synchronisation der Tafel für mehrere Nutzer

### ISSUE THREAD

**Issue by jonyschmid** [UniRegensburg/mme-ws2020-projekte-tatktiktafel-1#15]
Der aktuelle Zustand der Tafel (im jeweiligen Raum) wird für alle verbundenen Nutzer synchronisiert, sodass alle Nutzer die gleiche Tafel sehen. Die aktuell verbundenen Nutzer werden aufgelistet.

**Comment by jonyschmid** [comment]
Gezeichnetes wird übertragen.

**Comment by jhoffmann-se** [comment]
- Canvas https://github.com/UniRegensburg/mme-ws2020-projekte-tatktiktafel-1/commit/ad64ee1f54eb6b926e2f5429d91d55843d646974
- Draggables https://github.com/UniRegensburg/mme-ws2020-projekte-tatktiktafel-1/commit/c540708356667f16fe2393596a513905fd95a469
- Marker https://github.com/UniRegensburg/mme-ws2020-projekte-tatktiktafel-1/commit/e1674bc85d108fabe3da37d6cf64ac6a4f9d0419
- Utilities https://github.com/UniRegensburg/mme-ws2020-projekte-tatktiktafel-1/commit/e7c4becef145009a215d16179cf4a2d94afd0b7c
