### ISSUE TITLE
Private passwortgeschützte Lobbies/Räume

### ISSUE THREAD

**Issue by jonyschmid** [UniRegensburg/mme-ws2020-projekte-tatktiktafel-1#16]
Es können verschiedene Instanzen der Tafel erzeugt werden, damit mehrere Nutzergruppen/Teams das System gleichzeitig nutzen können.

**Comment by jhoffmann-se** [comment]
Closed by https://github.com/UniRegensburg/mme-ws2020-projekte-tatktiktafel-1/commit/1ae661d0323ae42c5e21c05220013fdfbf93f765
