### ISSUE TITLE
Landingpage

### ISSUE THREAD

**Issue by jonyschmid** [UniRegensburg/mme-ws2020-projekte-tatktiktafel-1#24]
Beim Öffnen der Webseite landen die Nutzer auf einer Landingpage, auf der sie einen neuen Raum erstellen oder einem Raum über einen Key beitreten können.

**Comment by lat26358** [comment]
Closed with pull-request https://github.com/UniRegensburg/mme-ws2020-projekte-tatktiktafel-1/pull/38
