### ISSUE TITLE
Colyseus-Client wird über script-Tag statt import-Statement importiert

### ISSUE THREAD

**Issue by jhoffmann-se** [UniRegensburg/mme-ws2020-projekte-tatktiktafel-1#4]
Siehe [app/index.html](https://github.com/UniRegensburg/mme-ws2020-projekte-tatktiktafel-1/blob/basic-server-client-with-colyseus/app/index.html).

![Discord-Screenshot](https://media.discordapp.net/attachments/806434325490565130/820983453830479882/unknown.png)

`import * as Colyseus from "colyseus.js"` wie in der [Dokumentation](https://docs.colyseus.io/getting-started/javascript-client/) beschrieben funktioniert hier nicht. `Colyseus` in der Konsole ausgeben ergibt hier ein Objekt vom Typ `Module`, von dem ich jetzt nicht näher weiß, wie ich damit zu interagieren habe, um an die gewünschten Exporte wie am Ende der [colyseus.js](https://github.com/UniRegensburg/mme-ws2020-projekte-tatktiktafel-1/blob/basic-server-client-with-colyseus/libs/colyseus.js/colyseus.js) sichtbar, speziell `Client`, heranzukommen.

Bis auf Weiteres wird die Library jetzt über HTML-Script-Tag importiert und `Colyseus` für eslint als globale Variable spezifiziert.

**Comment by alexanderbazo** [comment]
Ich vermute, dass die `import`-Syntax hier nicht funktionieren wird. Es schaut so aus, als ob der Inhalt der Client-Datei (`colyseus.js`) weder mit einem statischen noch einem [dynamischen Import](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import#dynamic_import) kompatibel ist. Möglicherweise würde es klappen, wenn die Datei durch ein entsprechendes Build-Tool (siehe [Dokumentation](https://docs.colyseus.io/getting-started/javascript-client/#including-the-javascript-sdk-in-your-project)) verwendet wird.

Der Ansatz, die Client-Bibliothek via `npm` zu installieren, über den *Express*-Server bereitzustellen  und dann per `<script>`-Tag einzubinden, erscheint mir ausreichend und gut umgesetzt. Die URL im *Tag* würde ich aber noch präzisieren: 

```
<script src="/libs/colyseus.js/colyseus.js"></script>
```

Die *ESLint*-Annotation für die globale Variable kann so weiter verwendet werden.
