### ISSUE TITLE
Auswählbare Map

### ISSUE THREAD

**Issue by jonyschmid** [UniRegensburg/mme-ws2020-projekte-tatktiktafel-1#7]
Die Nutzer können zwischen den Maps des Active-Duty-Map-Pools auswählen.

**Comment by jhoffmann-se** [comment]
https://github.com/UniRegensburg/mme-ws2020-projekte-tatktiktafel-1/commit/034640012aabfe1f14bfe30032efc673cfc35294

**Comment by jonyschmid** [comment]
https://github.com/UniRegensburg/mme-ws2020-projekte-tatktiktafel-1/commit/034640012aabfe1f14bfe30032efc673cfc35294

**Comment by jonyschmid** [comment]
https://github.com/UniRegensburg/mme-ws2020-projekte-tatktiktafel-1/commit/034640012aabfe1f14bfe30032efc673cfc35294
Karte wird synchronisiert geändert.
